### ISSUE TITLE
Login not taking to main activity page

### ISSUE THREAD

**Issue by TonyStark2007** [AbrarJahin/Android_Login-And-Register-User#1]
Hey hi, I tried your code. It worked flawlessly. thanks for it.
one prob I am facing is when I register a user and then log in, the new screen (main activity) show the name and mail as you programmed but when I logout and login again with the same credential it only shows plain text welcome..no user name and email this time.
I think its not able to retrieve data from sqlite or there is no data saved as when i logged out it cleared the sqlite data (I think you programmed it that way).

Can you tell me how to retain the data. It would be grateful. Thank you.

**Comment by aditya23jaitly** [comment]
delete db.deleteuser in activity main

**Comment by AbrarJahin** [comment]
Sorry to say that I am not finding this error @TonyStark2007 

Can you please write in detail so that I can fix that?

Thanks
